//! Integration tests for X11 input capture and playback
//! These tests require an X11 session (real or Xvfb) with DISPLAY set.
//!
//! To run: DISPLAY=:99 cargo test --test integration_x11 -- --test-threads=1

#[cfg(all(target_os = "linux", feature = "os-linux-input"))]
mod x11_tests {
    use loopautoma_lib::domain::{Automation, InputCapture, InputEvent, MouseButton};
    use loopautoma_lib::os::linux::{LinuxAutomation, LinuxInputCapture};
    use std::sync::{Arc, Mutex};
    use std::thread;
    use std::time::Duration;

    /// Test that input capture can be started and stopped without errors
    #[test]
    fn test_input_capture_lifecycle() {
        // Skip if no X11 session
        if std::env::var("DISPLAY").is_err() {
            eprintln!("Skipping test_input_capture_lifecycle: DISPLAY not set");
            return;
        }

        let mut capture = LinuxInputCapture::default();
        let events = Arc::new(Mutex::new(Vec::new()));
        let events_clone = events.clone();

        let callback = Arc::new(move |event: InputEvent| {
            events_clone.lock().unwrap().push(event);
        });

        // Start capture
        let result = capture.start(callback);
        if let Err(e) = &result {
            eprintln!("Input capture failed to start: {}", e);
            eprintln!("This may indicate:");
            eprintln!("  - X11 session not available");
            eprintln!("  - XInput2 extension not available");
            eprintln!("  - Missing packages: libxi-dev, libxtst-dev, libxkbcommon-x11-dev");
        }
        assert!(result.is_ok(), "Failed to start input capture: {:?}", result);

        // Let it run for a short time
        thread::sleep(Duration::from_millis(500));

        // Stop capture
        let result = capture.stop();
        assert!(result.is_ok(), "Failed to stop input capture: {:?}", result);

        println!("Input capture lifecycle test passed");
    }

    /// Test that automation commands can be executed without errors
    /// Note: This test may fail in Xvfb environment due to missing keyboard device
    #[test]
    fn test_automation_commands() {
        // Skip if no X11 session
        if std::env::var("DISPLAY").is_err() {
            eprintln!("Skipping test_automation_commands: DISPLAY not set");
            return;
        }

        let automation = match LinuxAutomation::new() {
            Ok(auto) => auto,
            Err(e) => {
                eprintln!("Failed to create LinuxAutomation: {}", e);
                eprintln!("This may indicate:");
                eprintln!("  - X11 session not available (e.g., running in Xvfb without keyboard)");
                eprintln!("  - XTest extension not available");
                eprintln!("  - Missing packages: libxtst-dev");
                eprintln!("NOTE: This is expected in Xvfb environments - not a code bug!");
                // Don't panic, just skip - this is expected in CI/Xvfb
                return;
            }
        };

        // Test cursor movement
        let result = automation.move_cursor(100, 100);
        assert!(result.is_ok(), "Failed to move cursor: {:?}", result);

        thread::sleep(Duration::from_millis(50));

        // Test mouse click
        let result = automation.click(MouseButton::Left);
        assert!(result.is_ok(), "Failed to click: {:?}", result);

        thread::sleep(Duration::from_millis(50));

        // Test typing
        let result = automation.type_text("test");
        assert!(result.is_ok(), "Failed to type text: {:?}", result);

        thread::sleep(Duration::from_millis(50));

        // Test special key
        let result = automation.key("Enter");
        assert!(result.is_ok(), "Failed to press Enter: {:?}", result);

        println!("Automation commands test passed");
    }

    /// Test that we can capture events generated by automation
    /// This is the critical integration test
    #[test]
    fn test_capture_automation_roundtrip() {
        // Skip if no X11 session
        if std::env::var("DISPLAY").is_err() {
            eprintln!("Skipping test_capture_automation_roundtrip: DISPLAY not set");
            return;
        }

        let automation = match LinuxAutomation::new() {
            Ok(auto) => auto,
            Err(e) => {
                eprintln!("Failed to create LinuxAutomation: {}", e);
                return;
            }
        };

        let mut capture = LinuxInputCapture::default();
        let events = Arc::new(Mutex::new(Vec::new()));
        let events_clone = events.clone();

        let callback = Arc::new(move |event: InputEvent| {
            println!("Captured event: {:?}", event);
            events_clone.lock().unwrap().push(event);
        });

        // Start capture
        let result = capture.start(callback);
        if result.is_err() {
            eprintln!("Input capture failed to start, skipping roundtrip test");
            return;
        }

        // Give capture time to initialize
        thread::sleep(Duration::from_millis(200));

        // Generate some events
        let _ = automation.move_cursor(200, 200);
        thread::sleep(Duration::from_millis(100));

        let _ = automation.click(MouseButton::Left);
        thread::sleep(Duration::from_millis(100));

        let _ = automation.type_text("x");
        thread::sleep(Duration::from_millis(100));

        // Stop capture
        let _ = capture.stop();

        // Check if we captured events
        let captured = events.lock().unwrap();
        println!("Captured {} events total", captured.len());

        // We should have captured at least some events
        // The exact count depends on timing and X11 event delivery
        if captured.is_empty() {
            eprintln!("WARNING: No events captured in roundtrip test");
            eprintln!("This may indicate:");
            eprintln!("  - Events are not being delivered to this process");
            eprintln!("  - XInput2 permissions issue");
            eprintln!("  - Window focus issue in X11");
        } else {
            println!("Successfully captured events in roundtrip test!");
        }
    }
}

// X11 integration tests are only available on Linux with os-linux-input feature.
// No tests will be run on other platforms.
